@startuml
@startuml


package common {
    package data {
        class Ticket {
            - int id
            - String name
            - Coordinates coordinates
            - LocalDateTime creationDate
            - Long price
            - TicketType type
            - Venue venue
            --
            + Ticket(int, String, Coordinates, LocalDateTime, Long, TicketType, Venue)
            + setID(int) void
            + setIdWithValid(int) void
            + getId() int
            + setName(String) void
            + getName() String
            + setCoordinates(Coordinates) void
            + getCoordinates() Coordinates
            + setCreationDate(LocalDateTime) void
            + getCreationDate() LocalDateTime
            + setPrice(Long) void
            + getPrice() Long
            + setType(TicketType) void
            + getType() TicketType
            + setVenue(Venue) void
            + getVenue() Venue
            + compareTo(Ticket) int
            + toString() String
        }

        class Coordinates {
            - int x
            - Long y
            --
            + Coordinates(int, Long)
            + setX(int) void
            + getX() int
            + setY(Long) void
            + getY() Long
            + toString() String
        }

        class Venue {
            - long id
            - String name
            - int capacity
            - Address address
            --
            + Venue(long, String, int, Address)
            + setId(long) void
            + getId() long
            + setName(String) void
            + getName() String
            + setCapacity(int) void
            + getCapacity() int
            + setAddress(Address) void
            + getAddress() Address
            + compareTo(Venue) int
            + toString() String
        }

        class Address {
            - String street
            - String zipCode
            - Location town
            --
            + Address(String, String, Location)
            + setStreet(String) void
            + getStreet() String
            + setZipCode(String) void
            + getZipCode() String
            + setTown(Location) void
            + getTown() Location
            + toString() String
        }

        class Location {
            - double x
            - Long y
            - Float z
            - String name
            --
            + Location(double, Long, Float, String)
            + setX(double) void
            + getX() double
            + setY(Long) void
            + getY() Long
            + setZ(Float) void
            + getZ() Float
            + setName(String) void
            + getName() String
            + toString() String
        }

        enum TicketType {
            VIP
            USUAL
            BUDGETARY
            CHEAP
            --
            + getDescription() String
            + AllDescriptions() String
        }
    }

    package network {
        class Request {
            - String commandName
            - String arg
            - Ticket ticket
            - Long price
            - TicketType type
            --
            + Request(String)
            + Request(String, String)
            + Request(String, Ticket)
            + Request(String, String, Ticket)
            + Request(String, Ticket, boolean)
            + Request(String, Long)
            + Request(String, TicketType)
            + getCommandName() String
            + getArg() String
            + getTicket() Ticket
            + getPrice() Long
            + getType() TicketType
        }

        class Response {
            - boolean success
            - String message
            - Object data
            --
            + Response(boolean, String)
            + Response(boolean, String, Object)
            + isSuccess() boolean
            + getMessage() String
            + getData() Object
        }
    }

    package commands {
        interface Command {
            + execute(TicketCollection, String, Object): Response
            + getDescription(): String
            + getName(): String
            + requiresTicket(): boolean
        }
    }
}

package server {

    class Server {
        - int port
        - String filename
        - TicketCollection collection
        - CommandExecutor executor
        - DatagramSocket socket
        - boolean running
        --
        + Server(int, String, TicketCollection)
        - loadCollection() void
        + saveCollection() void
        + start() void
        + stop() void
        + main(String[]) void
    }

    class CommandExecutor {
        - Map<String, Command> commands
        - TicketCollection collection
        - String filename
        --
        + CommandExecutor(TicketCollection, String)
        - addAllCommands() void
        + getCommands() Map
        + execute(Request): Response
    }

    class TicketCollection {
        - ArrayDeque<Ticket> collection
        - LocalDateTime initializationDate
        --
        + TicketCollection()
        + addElement(Ticket) void
        + update(int, Ticket) boolean
        + removeById(int) boolean
        + clear() void
        + getFirst() Ticket
        + removeFirst() Ticket
        + removeGreater(Ticket) int
        + removeAllByPrice(Long) int
        + removeAnyByType(TicketType) boolean
        + minByVenue() Ticket
        + getInfo() String
        + showAll() String
        + getCollection() ArrayDeque
        + size() int
        - sortCollection() void
    }

    package server.commands {
        class AddCommand implements Command
        {
                + execute() void
                + getDescription() String
                + getName() String
                + requiresTicket() boolean
            }
        class ShowCommand implements Command
        {
                + execute() void
                + getDescription() String
                + getName() String
                + requiresTicket() boolean
            }
        class UpdateCommand implements Command{
                + execute() void
                + findTicketById(int) Ticket
                + getDescription() String
                + getName() String
                + requiresTicket() boolean
            }
        class RemoveByIdCommand implements Command
        {
                + execute() void
                + getDescription() String
                + getName() String
                + requiresTicket() boolean
            }
        class ClearCommand implements Command
        {
                + execute() void
                + getDescription() String
                + getName() String
                + requiresTicket() boolean
            }
        class HeadCommand implements Command
        {
                + execute() void
                + getDescription() String
                + getName() String
                + requiresTicket() boolean
            }
        class RemoveHeadCommand implements Command
        {
                + execute() void
                + getDescription() String
                + getName() String
            }
        class RemoveGreaterCommand implements Command
        {
                + execute() void
                + getDescription() String
                + getName() String
                + requiresTicket() boolean
            }
        class RemoveAllByPriceCommand implements Command
        {
                + execute() void
                + getDescription() String
                + getName() String
                + requiresTicket() boolean
            }
        class RemoveAnyByTypeCommand implements Command
        {
                + execute() void
                + getDescription() String
                + getName() String
                + requiresTicket() boolean
            }
        class MinByVenueCommand implements Command
        {
                + execute() void
                + getDescription() String
                + getName() String
                + requiresTicket() boolean
        }
        class HelpCommand implements Command
        {
                - CommandExecutor executor;

                + HelpCommand(ManagerOfCommands)
                + execute() void
                + getDescription() String
                + getName() String
                + requiresTicket() boolean
            }
        class InfoCommand implements Command
        {
                    + execute() void
                    + getDescription() String
                    + getName() String
                    + requiresTicket() boolean
            }
        class SaveCommand implements Command
        {
                - String filename
                - TicketCollection collection

                + execute() void
                + getDescription() String
                + getName() String
                + requiresTicket() boolean
            }
    }

    package server.util {
        class CreateID {
            - Set<Integer> ticketID
            - Set<Long> venueID
            --
            + createTicketID() int
            + createVenueID() long
            + removeTicketID(int) void
            + removeVenueID(long) void
            + addTicketID(int) void
            + addVenueID(long) void
        }

        class Parser {
            - DateTimeFormatter DATE_FORMATTER
            --
            + parseFile(String): ArrayDeque<Ticket>
            - parseOneLine(String): Ticket
            + saveTicketToCSV(Ticket): StringBuilder
            + saveFileToCSV(ArrayDeque, String) void
        }
    }
}

package client {

    class Client {
        - int max_retries
        - int timeout
        - String host
        - int port
        - DatagramChannel channel
        - SocketAddress serverAddress
        - LineReader reader
        - boolean running
        --
        + Client(String, int)
        - initConsole() void
        + start() void
        - processCommand(String) void
        - buildRequest(String, String): Request
        - executeScript(String) void
        - sendWithRetry(Request): Response
        - printResponse(Response) void
        + main(String[]) void
    }

    class ConsoleReader {
        - Scanner scanner
        - boolean scriptRegime
        - Scanner scriptScanner
        - int scriptLineNumber
        - boolean hasPeeked
        - String nextLine
        --
        + setScriptRegime(Scanner) void
        + setInteractiveRegime() void
        + isScriptRegime() boolean
        - commandFlag(String): boolean
        - readLine(): String
        + peekNextLine(): String
        + readNextCommand(): String
        + readStr(String): String
        + readInt(String): int
        + readDouble(String): double
        + readLongNotNull(String): Long
        + readFloatNotNull(String): Float
        + readNotEmptyStr(String): String
        + readStreet(String): String
        + readLocationName(String): String
        + readPrice(String): Long
        + readTicketType(): TicketType
        + readYN(String): boolean
        + readCoordinates(): Coordinates
        + readLocation(): Location
        + readAddress(): Address
        + readVenue(): Venue
        + readTicket(String): Ticket
        + readTicket(): Ticket
    }
}


Ticket -- Coordinates
Ticket -- TicketType
Ticket -- Venue
Venue -- Address
Address -- Location

Server -- TicketCollection
Server -- CommandExecutor
CommandExecutor -- TicketCollection
CommandExecutor --> Command
Command <|-- server.commands.AddCommand
Command <|-- server.commands.ShowCommand
Command <|-- server.commands.UpdateCommand
Command <|-- server.commands.RemoveByIdCommand
Command <|-- server.commands.ClearCommand
Command <|-- server.commands.HeadCommand
Command <|-- server.commands.RemoveHeadCommand
Command <|-- server.commands.RemoveGreaterCommand
Command <|-- server.commands.RemoveAllByPriceCommand
Command <|-- server.commands.RemoveAnyByTypeCommand
Command <|-- server.commands.MinByVenueCommand
Command <|-- server.commands.HelpCommand
Command <|-- server.commands.InfoCommand
Command <|-- server.commands.SaveCommand


Client --> Request
Client --> Response
Client --> ConsoleReader
Client ..> server.util.CreateID : uses (only for Venue id=0)


Server ..> Request : receives
Server ..> Response : sends
Client ..> Request : sends
Client ..> Response : receives


Server --> DatagramSocket
Client --> DatagramChannel

@enduml
